name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:

  Deploy-Production:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        run: sudo apt-get install -y python3 python3-pip

      - name: Install Dependencies
        run: |
          cd flask-app
          pip install -r requirements.txt 
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
       
      - name: Pull Vercel Environment Information
        run: | 
          cd flask-app/api
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: |
          cd flask-app/api
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          cd flask-app/api
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}